version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:4.0.2-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
