# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fibo.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'fibo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfibo.proto\x12\x04\x66ibo\x1a google/protobuf/descriptor.proto\"\x1b\n\x0b\x46iboRequest\x12\x0c\n\x01n\x18\x01 \x01(\x04R\x01n\"&\n\x0c\x46iboResponse\x12\x16\n\x06result\x18\x01 \x01(\x04R\x06result2D\n\x04\x46ibo\x12<\n\tCountFibo\x12\x11.fibo.FiboRequest\x1a\x12.fibo.FiboResponse\"\x08\xca\xb2\x04\x04test:>\n\x08\x65xchange\x12\x1e.google.protobuf.MethodOptions\x18\xa9\x46 \x01(\tR\x08\x65xchange\x88\x01\x01\x42\x45\n\x08\x63om.fiboB\tFiboProtoP\x01\xa2\x02\x03\x46XX\xaa\x02\x04\x46ibo\xca\x02\x04\x46ibo\xe2\x02\x10\x46ibo\\GPBMetadata\xea\x02\x04\x46ibob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fibo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\010com.fiboB\tFiboProtoP\001\242\002\003FXX\252\002\004Fibo\312\002\004Fibo\342\002\020Fibo\\GPBMetadata\352\002\004Fibo'
  _globals['_FIBO'].methods_by_name['CountFibo']._loaded_options = None
  _globals['_FIBO'].methods_by_name['CountFibo']._serialized_options = b'\312\262\004\004test'
  _globals['_FIBOREQUEST']._serialized_start=54
  _globals['_FIBOREQUEST']._serialized_end=81
  _globals['_FIBORESPONSE']._serialized_start=83
  _globals['_FIBORESPONSE']._serialized_end=121
  _globals['_FIBO']._serialized_start=123
  _globals['_FIBO']._serialized_end=191
# @@protoc_insertion_point(module_scope)
