# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greetings.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'greetings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgreetings.proto\x12\tgreetings\x1a google/protobuf/descriptor.proto\"%\n\x0fGreetingRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\",\n\x10GreetingResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2\x9d\x01\n\x0fGreetingService\x12\x45\n\x08SayHello\x12\x1a.greetings.GreetingRequest\x1a\x1b.greetings.GreetingResponse\"\x00\x12\x43\n\x06\x44oFail\x12\x1a.greetings.GreetingRequest\x1a\x1b.greetings.GreetingResponse\"\x00\x42\x63\n\rcom.greetingsB\x0eGreetingsProtoP\x01\xa2\x02\x03GXX\xaa\x02\tGreetings\xca\x02\tGreetings\xe2\x02\x15Greetings\\GPBMetadata\xea\x02\tGreetingsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greetings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.greetingsB\016GreetingsProtoP\001\242\002\003GXX\252\002\tGreetings\312\002\tGreetings\342\002\025Greetings\\GPBMetadata\352\002\tGreetings'
  _globals['_GREETINGREQUEST']._serialized_start=64
  _globals['_GREETINGREQUEST']._serialized_end=101
  _globals['_GREETINGRESPONSE']._serialized_start=103
  _globals['_GREETINGRESPONSE']._serialized_end=147
  _globals['_GREETINGSERVICE']._serialized_start=150
  _globals['_GREETINGSERVICE']._serialized_end=307
# @@protoc_insertion_point(module_scope)
