# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/greeting.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'proto/greeting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/greeting.proto\x12\x08greeting\"%\n\x0fGreetingRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"*\n\x10GreetingResponse\x12\x16\n\x06result\x18\x02 \x01(\tR\x06resultB]\n\x0c\x63om.greetingB\rGreetingProtoP\x01\xa2\x02\x03GXX\xaa\x02\x08Greeting\xca\x02\x08Greeting\xe2\x02\x14Greeting\\GPBMetadata\xea\x02\x08Greetingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.greeting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.greetingB\rGreetingProtoP\001\242\002\003GXX\252\002\010Greeting\312\002\010Greeting\342\002\024Greeting\\GPBMetadata\352\002\010Greeting'
  _globals['_GREETINGREQUEST']._serialized_start=34
  _globals['_GREETINGREQUEST']._serialized_end=71
  _globals['_GREETINGRESPONSE']._serialized_start=73
  _globals['_GREETINGRESPONSE']._serialized_end=115
# @@protoc_insertion_point(module_scope)
