name: publish release

on:
  release:
    types: [published]

jobs:
  buf:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          lint: false
          format: false
          breaking: false
          push: true
          token: ${{ secrets.BUF_TOKEN }}

  pypi:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: abatilo/actions-poetry@v2
      - name: Poetry build
        run: poetry build -n
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
