name: pull request checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  venv:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
    env:
      OS: ubuntu
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Configure poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
      - name: Cache venv
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
      - name: Install project dependencies
        run: poetry install --all-extras

  buf:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          breaking_against: 'https://github.com/zerlok/BrokRPC.git#branch=main'
          push: false

  lint:
    needs: venv
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Configure poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
      - name: Cache venv
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
          fail-on-cache-miss: 'true'
      - name: Show poetry env info
        run: poetry env info
      - name: Run mypy
        run: poetry run mypy
      - name: Run ruff check
        run: poetry run ruff check
      - name: Run ruff format
        run: poetry run ruff format --check

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:4.0.2-alpine
        ports:
          - 5672:5672
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
    env:
      OS: ubuntu
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Configure poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
      - name: Cache venv
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
          fail-on-cache-miss: 'true'
      - name: Show poetry env info
        run: poetry env info
      - name: Run pytest
        run: poetry run pytest --broker-url=amqp://guest:guest@localhost:5672/ --broker-retry-delay=3 --broker-retry-delay-mode=constant --broker-retries-limit=10 --cov-report=xml
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
